### ISSUE TITLE
The Lucky Wheel! ^^

### ISSUE THREAD

**Issue by Nathantolose** [dqle/Archero-Farmer#1]
Hello I would like to participate as a tester, I don't know programming but i would love to give you feedback on this lovely project you are working on! 

![imagen](https://user-images.githubusercontent.com/79171866/108196013-e16b6e00-7118-11eb-954d-0386089a9db0.png)
Lucky wheel it's been little blocker for me lately. I'm using your specs on resolution and cores but I can percieve that the screengrab it has lower quality than your actual "images" Folder so after some testing and checking yesterday night I found the issue, the game needs to be set on the settings options on "high" instead of "medium". Especify that on the documentation just to make sure an idiot like me can Set it correctly xD

Hope I can give you better feedback on my future comments ^^

**Comment by dqle** [comment]
Thank you! I've updated the documentation to include setting Archero Graphic settings to High!
